name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Install dependency
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -y build-essential chromium-browser
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Run test
        run: bin/rails test
